[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  omit_hostname = true

# Expose metrics in Prometheus format on port 9273
[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2

# Read metrics from the local Docker daemon
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  timeout = "5s"